using System.Collections.Generic;
using UnityEngine;

// Plays the creature's looping idle / walking motion as a real (legacy)
// AnimationClip through an Animation component. The clip is generated by
// CreatureMotion from the bone skeleton -- the topology is random, so there is
// nothing to hand-key -- and is exposed (Clip / MotionData) so GltfExporter can
// write the same animation into the exported .glb.
//
// Legacy, because AnimationClip.SetCurve only works at runtime on legacy clips.
[RequireComponent(typeof(Animation))]
public class CreatureIdleSway : MonoBehaviour
{
    private const string ClipName = "creature_motion";

    public AnimationClip Clip { get; private set; }
    public CreatureMotion.Data MotionData { get; private set; }

    private Animation anim;
    private SkinnedMeshRenderer skin;
    private Transform rootBone;
    private CreatureGenerator.AnimationMode currentMode = (CreatureGenerator.AnimationMode)(-1);

    private readonly Dictionary<Transform, Quaternion> restRotation = new Dictionary<Transform, Quaternion>();
    private readonly Dictionary<Transform, Vector3> restPosition = new Dictionary<Transform, Vector3>();

    // Called by CreatureGenerator.AddIdleAnimation when the skeleton is freshly
    // built (bones at rest). Captures the rest pose once, here -- ConfigureForMode
    // reuses it, so an Idle<->Walking switch never re-samples a mid-animation pose.
    public void Initialize(SkinnedMeshRenderer smr, CreatureGenerator.AnimationMode mode)
    {
        skin = smr;
        rootBone = smr != null ? smr.rootBone : null;
        if (rootBone == null)
        {
            enabled = false;
            return;
        }

        restRotation.Clear();
        restPosition.Clear();
        CaptureRest(rootBone);

        Rebuild(mode);
    }

    public void ConfigureForMode(CreatureGenerator.AnimationMode mode)
    {
        if (rootBone != null && mode != currentMode)
        {
            Rebuild(mode);
        }
    }

    // Snaps every bone back to the pose captured in Initialize. The Animation
    // component re-poses them on the next frame, so this is only meant for a
    // synchronous read right after (see GltfExporter -- the exported skeleton
    // must be at rest to match the mesh's bind poses).
    public void ApplyRestPose()
    {
        foreach (KeyValuePair<Transform, Quaternion> kv in restRotation)
        {
            if (kv.Key != null)
            {
                kv.Key.localRotation = kv.Value;
            }
        }
        foreach (KeyValuePair<Transform, Vector3> kv in restPosition)
        {
            if (kv.Key != null)
            {
                kv.Key.localPosition = kv.Value;
            }
        }
    }

    private void CaptureRest(Transform bone)
    {
        restRotation[bone] = bone.localRotation;
        restPosition[bone] = bone.localPosition;
        for (int i = 0; i < bone.childCount; i++)
        {
            CaptureRest(bone.GetChild(i));
        }
    }

    private void Rebuild(CreatureGenerator.AnimationMode mode)
    {
        currentMode = mode;

        if (anim == null)
        {
            anim = GetComponent<Animation>();
            anim.playAutomatically = false;
            anim.cullingType = AnimationCullingType.AlwaysAnimate; // bones swing past the baked bounds
        }

        if (anim.GetClip(ClipName) != null)
        {
            anim.RemoveClip(ClipName);
        }
        DestroyClip();

        MotionData = CreatureMotion.Build(rootBone, skin.bones, transform, restRotation, restPosition, mode);
        Clip = CreatureMotion.BuildClip(MotionData, ClipName);

        anim.AddClip(Clip, ClipName);
        anim.wrapMode = WrapMode.Loop;
        AnimationState state = anim[ClipName];
        if (state != null)
        {
            state.wrapMode = WrapMode.Loop;
        }
        anim.Play(ClipName);
    }

    private void DestroyClip()
    {
        if (Clip == null)
        {
            return;
        }
        if (Application.isPlaying)
        {
            Destroy(Clip);
        }
        else
        {
            DestroyImmediate(Clip);
        }
        Clip = null;
    }

    void OnDestroy()
    {
        if (anim != null && anim.GetClip(ClipName) != null)
        {
            anim.RemoveClip(ClipName);
        }
        DestroyClip();
    }
}
